'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WsSDWCF
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_ISDWCF", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SDWCF
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ActualizaEstadoDocumentoElectronicoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaCedulaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReenvioDocumentoElectronicoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Business.My.MySettings.Default.Business_WsSDWCF_SDWCF
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ActualizaEstadoDocumentoElectronicoCompleted As ActualizaEstadoDocumentoElectronicoCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaCedulaCompleted As ConsultaCedulaCompletedEventHandler
        
        '''<remarks/>
        Public Event ReenvioDocumentoElectronicoCompleted As ReenvioDocumentoElectronicoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISDWCF/ActualizaEstadoDocumentoElectronico", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ActualizaEstadoDocumentoElectronico(ByVal pDocumento As DTActualizaDocumentoElectronico) As String
            Dim results() As Object = Me.Invoke("ActualizaEstadoDocumentoElectronico", New Object() {pDocumento})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ActualizaEstadoDocumentoElectronicoAsync(ByVal pDocumento As DTActualizaDocumentoElectronico)
            Me.ActualizaEstadoDocumentoElectronicoAsync(pDocumento, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ActualizaEstadoDocumentoElectronicoAsync(ByVal pDocumento As DTActualizaDocumentoElectronico, ByVal userState As Object)
            If (Me.ActualizaEstadoDocumentoElectronicoOperationCompleted Is Nothing) Then
                Me.ActualizaEstadoDocumentoElectronicoOperationCompleted = AddressOf Me.OnActualizaEstadoDocumentoElectronicoOperationCompleted
            End If
            Me.InvokeAsync("ActualizaEstadoDocumentoElectronico", New Object() {pDocumento}, Me.ActualizaEstadoDocumentoElectronicoOperationCompleted, userState)
        End Sub
        
        Private Sub OnActualizaEstadoDocumentoElectronicoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ActualizaEstadoDocumentoElectronicoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ActualizaEstadoDocumentoElectronicoCompleted(Me, New ActualizaEstadoDocumentoElectronicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISDWCF/ConsultaCedula", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaCedula(ByVal pCedula As String) As TPersona
            Dim results() As Object = Me.Invoke("ConsultaCedula", New Object() {pCedula})
            Return CType(results(0),TPersona)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaCedulaAsync(ByVal pCedula As String)
            Me.ConsultaCedulaAsync(pCedula, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaCedulaAsync(ByVal pCedula As String, ByVal userState As Object)
            If (Me.ConsultaCedulaOperationCompleted Is Nothing) Then
                Me.ConsultaCedulaOperationCompleted = AddressOf Me.OnConsultaCedulaOperationCompleted
            End If
            Me.InvokeAsync("ConsultaCedula", New Object() {pCedula}, Me.ConsultaCedulaOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaCedulaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaCedulaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaCedulaCompleted(Me, New ConsultaCedulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISDWCF/ReenvioDocumentoElectronico", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReenvioDocumentoElectronico(ByVal pEmisor_Id As Integer, ByVal pDoc_Id As Long, ByVal pEmail As String) As String
            Dim results() As Object = Me.Invoke("ReenvioDocumentoElectronico", New Object() {pEmisor_Id, pDoc_Id, pEmail})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReenvioDocumentoElectronicoAsync(ByVal pEmisor_Id As Integer, ByVal pDoc_Id As Long, ByVal pEmail As String)
            Me.ReenvioDocumentoElectronicoAsync(pEmisor_Id, pDoc_Id, pEmail, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReenvioDocumentoElectronicoAsync(ByVal pEmisor_Id As Integer, ByVal pDoc_Id As Long, ByVal pEmail As String, ByVal userState As Object)
            If (Me.ReenvioDocumentoElectronicoOperationCompleted Is Nothing) Then
                Me.ReenvioDocumentoElectronicoOperationCompleted = AddressOf Me.OnReenvioDocumentoElectronicoOperationCompleted
            End If
            Me.InvokeAsync("ReenvioDocumentoElectronico", New Object() {pEmisor_Id, pDoc_Id, pEmail}, Me.ReenvioDocumentoElectronicoOperationCompleted, userState)
        End Sub
        
        Private Sub OnReenvioDocumentoElectronicoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReenvioDocumentoElectronicoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReenvioDocumentoElectronicoCompleted(Me, New ReenvioDocumentoElectronicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DTActualizaDocumentoElectronico
        
        Private emisor_IdField As Integer
        
        Private doc_IdField As Long
        
        Private claveField As String
        
        Private estado_IdField As Integer
        
        '''<remarks/>
        Public Property Emisor_Id() As Integer
            Get
                Return Me.emisor_IdField
            End Get
            Set
                Me.emisor_IdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Doc_Id() As Long
            Get
                Return Me.doc_IdField
            End Get
            Set
                Me.doc_IdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Clave() As String
            Get
                Return Me.claveField
            End Get
            Set
                Me.claveField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Estado_Id() As Integer
            Get
                Return Me.estado_IdField
            End Get
            Set
                Me.estado_IdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class TPersona
        
        Private cedulaField As String
        
        Private nombreField As String
        
        Private apellido1Field As String
        
        Private apellido2Field As String
        
        Private nombreCompletoField As String
        
        Private errorCodeField As String
        
        Private errorDescriptionField As String
        
        '''<remarks/>
        Public Property Cedula() As String
            Get
                Return Me.cedulaField
            End Get
            Set
                Me.cedulaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Apellido1() As String
            Get
                Return Me.apellido1Field
            End Get
            Set
                Me.apellido1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Apellido2() As String
            Get
                Return Me.apellido2Field
            End Get
            Set
                Me.apellido2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreCompleto() As String
            Get
                Return Me.nombreCompletoField
            End Get
            Set
                Me.nombreCompletoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                Me.errorDescriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub ActualizaEstadoDocumentoElectronicoCompletedEventHandler(ByVal sender As Object, ByVal e As ActualizaEstadoDocumentoElectronicoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ActualizaEstadoDocumentoElectronicoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub ConsultaCedulaCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaCedulaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaCedulaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TPersona
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TPersona)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub ReenvioDocumentoElectronicoCompletedEventHandler(ByVal sender As Object, ByVal e As ReenvioDocumentoElectronicoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReenvioDocumentoElectronicoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
