'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace TiempoAireWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AloIntegraLTI", [Namespace]:="http://www.lticr.com/ALO-JIMMY/")>  _
    Partial Public Class AloIntegraLTI
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private PingOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProcesoGeneralOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.PuntoVenta.My.MySettings.Default.PuntoVenta_TiempoAireWS_AloPos
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event PingCompleted As PingCompletedEventHandler
        
        '''<remarks/>
        Public Event ProcesoGeneralCompleted As ProcesoGeneralCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lticr.com/ALO-JIMMY/Ping", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function Ping(<System.Xml.Serialization.XmlElementAttribute("Ping", [Namespace]:="http://www.lticr.com/ALO-JIMMY/")> ByVal Ping1 As Ping) As <System.Xml.Serialization.XmlElementAttribute("Pong", [Namespace]:="http://www.lticr.com/ALO-JIMMY/")> Pong
            Dim results() As Object = Me.Invoke("Ping", New Object() {Ping1})
            Return CType(results(0),Pong)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PingAsync(ByVal Ping1 As Ping)
            Me.PingAsync(Ping1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PingAsync(ByVal Ping1 As Ping, ByVal userState As Object)
            If (Me.PingOperationCompleted Is Nothing) Then
                Me.PingOperationCompleted = AddressOf Me.OnPingOperationCompleted
            End If
            Me.InvokeAsync("Ping", New Object() {Ping1}, Me.PingOperationCompleted, userState)
        End Sub
        
        Private Sub OnPingOperationCompleted(ByVal arg As Object)
            If (Not (Me.PingCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PingCompleted(Me, New PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lticr.com/ALO-JIMMY/ProcesoGeneral", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ProcesoGeneral(<System.Xml.Serialization.XmlElementAttribute("ProcesoGeneral", [Namespace]:="http://www.lticr.com/ALO-JIMMY/")> ByVal ProcesoGeneral1 As ProcesoGeneral) As <System.Xml.Serialization.XmlElementAttribute("TransaccionOutput", [Namespace]:="http://www.lticr.com/ALO-JIMMY/")> TransaccionOutput
            Dim results() As Object = Me.Invoke("ProcesoGeneral", New Object() {ProcesoGeneral1})
            Return CType(results(0),TransaccionOutput)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProcesoGeneralAsync(ByVal ProcesoGeneral1 As ProcesoGeneral)
            Me.ProcesoGeneralAsync(ProcesoGeneral1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProcesoGeneralAsync(ByVal ProcesoGeneral1 As ProcesoGeneral, ByVal userState As Object)
            If (Me.ProcesoGeneralOperationCompleted Is Nothing) Then
                Me.ProcesoGeneralOperationCompleted = AddressOf Me.OnProcesoGeneralOperationCompleted
            End If
            Me.InvokeAsync("ProcesoGeneral", New Object() {ProcesoGeneral1}, Me.ProcesoGeneralOperationCompleted, userState)
        End Sub
        
        Private Sub OnProcesoGeneralOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProcesoGeneralCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProcesoGeneralCompleted(Me, New ProcesoGeneralCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.lticr.com/ALO-JIMMY/")>  _
    Partial Public Class Ping
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.lticr.com/ALO-JIMMY/")>  _
    Partial Public Class tipoTransaccion
        
        Private operacionField As String
        
        Private servicioField As String
        
        Private telefonoField As String
        
        Private montoField As String
        
        Private vendedorField As String
        
        Private documentoField As String
        
        Private fechaField As String
        
        '''<remarks/>
        Public Property Operacion() As String
            Get
                Return Me.operacionField
            End Get
            Set
                Me.operacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Servicio() As String
            Get
                Return Me.servicioField
            End Get
            Set
                Me.servicioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Telefono() As String
            Get
                Return Me.telefonoField
            End Get
            Set
                Me.telefonoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Monto() As String
            Get
                Return Me.montoField
            End Get
            Set
                Me.montoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Vendedor() As String
            Get
                Return Me.vendedorField
            End Get
            Set
                Me.vendedorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Documento() As String
            Get
                Return Me.documentoField
            End Get
            Set
                Me.documentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.lticr.com/ALO-JIMMY/")>  _
    Partial Public Class tipoSeguridad
        
        Private entidadField As String
        
        Private usuarioField As String
        
        Private claveField As String
        
        '''<remarks/>
        Public Property Entidad() As String
            Get
                Return Me.entidadField
            End Get
            Set
                Me.entidadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Clave() As String
            Get
                Return Me.claveField
            End Get
            Set
                Me.claveField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.lticr.com/ALO-JIMMY/")>  _
    Partial Public Class Pong
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.lticr.com/ALO-JIMMY/")>  _
    Partial Public Class ProcesoGeneral
        
        Private seguridadField As tipoSeguridad
        
        Private transaccionField As tipoTransaccion
        
        '''<remarks/>
        Public Property Seguridad() As tipoSeguridad
            Get
                Return Me.seguridadField
            End Get
            Set
                Me.seguridadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transaccion() As tipoTransaccion
            Get
                Return Me.transaccionField
            End Get
            Set
                Me.transaccionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.lticr.com/ALO-JIMMY/")>  _
    Partial Public Class TransaccionOutput
        
        Private operacionField As String
        
        Private servicioField As String
        
        Private telefonoField As String
        
        Private montoField As String
        
        Private vendedorField As String
        
        Private documentoField As String
        
        Private fechaField As String
        
        Private transProveedorField As String
        
        Private reciboField As String
        
        Private serieField As String
        
        Private comisionField As String
        
        Private saldoField As String
        
        Private errorCodigoField As String
        
        Private errorDesField As String
        
        Private recargaEstadoField As String
        
        Private recargaDetalleField As String
        
        '''<remarks/>
        Public Property Operacion() As String
            Get
                Return Me.operacionField
            End Get
            Set
                Me.operacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Servicio() As String
            Get
                Return Me.servicioField
            End Get
            Set
                Me.servicioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Telefono() As String
            Get
                Return Me.telefonoField
            End Get
            Set
                Me.telefonoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Monto() As String
            Get
                Return Me.montoField
            End Get
            Set
                Me.montoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Vendedor() As String
            Get
                Return Me.vendedorField
            End Get
            Set
                Me.vendedorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Documento() As String
            Get
                Return Me.documentoField
            End Get
            Set
                Me.documentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransProveedor() As String
            Get
                Return Me.transProveedorField
            End Get
            Set
                Me.transProveedorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Recibo() As String
            Get
                Return Me.reciboField
            End Get
            Set
                Me.reciboField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Comision() As String
            Get
                Return Me.comisionField
            End Get
            Set
                Me.comisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Saldo() As String
            Get
                Return Me.saldoField
            End Get
            Set
                Me.saldoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorCodigo() As String
            Get
                Return Me.errorCodigoField
            End Get
            Set
                Me.errorCodigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorDes() As String
            Get
                Return Me.errorDesField
            End Get
            Set
                Me.errorDesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RecargaEstado() As String
            Get
                Return Me.recargaEstadoField
            End Get
            Set
                Me.recargaEstadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RecargaDetalle() As String
            Get
                Return Me.recargaDetalleField
            End Get
            Set
                Me.recargaDetalleField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub PingCompletedEventHandler(ByVal sender As Object, ByVal e As PingCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PingCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Pong
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Pong)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub ProcesoGeneralCompletedEventHandler(ByVal sender As Object, ByVal e As ProcesoGeneralCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProcesoGeneralCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TransaccionOutput
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TransaccionOutput)
            End Get
        End Property
    End Class
End Namespace
